"use client"

import { Card } from "@/components/ui/Card"
import { Badge } from "@/components/ui/Badge"
import { Button } from "@/components/ui/Button"
import { Compass, Search, Filter } from "lucide-react"
import Link from "next/link"

const EXPLORE_PROJECTS = [
  {
    name: "AegisAI",
    tagline: "Intelligent Student Cybersecurity Guardian",
    domain: "Cybersecurity",
    difficulty: "Intermediate",
    tech: ["Python", "Next.js", "ML"],
  },
  {
    name: "AgroSmart",
    tagline: "Precision Farming and Disease Detection using CV",
    domain: "AgriTech",
    difficulty: "Advanced",
    tech: ["TensorFlow", "React Native", "IoT"],
  },
  {
    name: "FinLearn",
    tagline: "Gamified Financial Literacy App for Gen Z",
    domain: "FinTech",
    difficulty: "Beginner",
    tech: ["React", "Firebase", "Node.js"],
  },
  {
    name: "MedSync",
    tagline: "Decentralized Patient Record Management",
    domain: "HealthTech",
    difficulty: "Advanced",
    tech: ["Solidity", "Next.js", "IPFS"],
  },
  {
    name: "SignaText",
    tagline: "Real-time Sign Language to Text Translation",
    domain: "AI/ML",
    difficulty: "Advanced",
    tech: ["OpenCV", "PyTorch", "Python"],
  },
  {
    name: "CampusRide",
    tagline: "Peer-to-peer Carpooling for University Students",
    domain: "App Dev",
    difficulty: "Intermediate",
    tech: ["Flutter", "Firebase", "Maps API"],
  },
  {
    name: "StudyBuddy AI",
    tagline: "Personalized Roadmap Generator for Exams",
    domain: "EdTech",
    difficulty: "Intermediate",
    tech: ["OpenAI API", "React", "Express"],
  },
  {
    name: "EcoTrack",
    tagline: "Personal Carbon Footprint Tracker and Recommender",
    domain: "Sustainability",
    difficulty: "Beginner",
    tech: ["Vue.js", "Supabase"],
  }
]

export default function ExplorePage() {
  return (
    <div className="container mx-auto px-4 py-12 max-w-7xl space-y-8">
      <div className="text-center max-w-2xl mx-auto mb-12">
        <h1 className="text-4xl font-bold mb-4 flex items-center justify-center gap-3">
          <Compass className="text-primary w-10 h-10" /> Explore Projects
        </h1>
        <p className="text-xl text-muted">Browse through highly-rated project concepts generated by our AI.</p>
      </div>

      <div className="flex gap-4 mb-8">
        <div className="relative flex-1">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-muted" />
          <input 
            type="text" 
            placeholder="Search projects, domains, technologies..." 
            className="w-full bg-surface border border-border rounded-lg pl-10 pr-4 py-3 focus:outline-none focus:border-primary"
          />
        </div>
        <Button variant="outline" className="gap-2"><Filter className="w-4 h-4"/> Filter</Button>
      </div>

      <div className="grid md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
        {EXPLORE_PROJECTS.map((project, i) => (
          <Card key={i} className="flex flex-col hover:border-primary/50 transition-colors group">
            <div className="p-5 flex-1">
              <div className="flex justify-between items-start mb-3">
                <Badge variant="accent">{project.domain}</Badge>
                <span className="text-xs text-muted">{project.difficulty}</span>
              </div>
              <h3 className="text-xl font-bold mb-2 group-hover:text-primary transition-colors">{project.name}</h3>
              <p className="text-sm text-muted mb-4">{project.tagline}</p>
              <div className="flex flex-wrap gap-1 mt-auto">
                {project.tech.map(t => (
                  <span key={t} className="text-[10px] px-2 py-1 bg-surface-hover rounded-md text-foreground">{t}</span>
                ))}
              </div>
            </div>
            <div className="p-4 border-t border-border/50 bg-surface/30">
              <Link href={i === 0 ? "/project/demo" : "#"}>
                <Button variant="ghost" className="w-full justify-between group-hover:bg-primary/10 group-hover:text-primary">
                  View Architecture <Compass className="w-4 h-4" />
                </Button>
              </Link>
            </div>
          </Card>
        ))}
      </div>
    </div>
  )
}
